user_usuario:
    resource: "@UserBundle/Controller/UsuarioController.php"
    type:     annotation

empresa_empresa:
    resource: "@EmpresaBundle/Controller/EmpresaController.php"
    type:     annotation

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

empresa:
    resource: "@EmpresaBundle/Resources/config/routing.yml"
    prefix:   /empresa
    
login_check:
    pattern: /login_check 

app:
    resource: '@AppBundle/Controller/'
    type: annotation
