 

activo_homepage:
    path:     /activo
    defaults: { _controller: ActivoBundle:activo:index }

activo_new:
    path:     /activo/new
    defaults: { _controller: ActivoBundle:activo:new }

activo_index:
    path:     /activo/index
    defaults: { _controller: ActivoBundle:activo:index }

activo_edit:
    path:     /activo/edit
    defaults: { _controller: ActivoBundle:activo:edit }

activo_show:
    path:     /activo/show
    defaults: { _controller: ActivoBundle:activo:show }

activo_delete:
    path:     /activo/delete
    defaults: { _controller: ActivoBundle:activo:delete }

categoria_homepage:
    path:     /categoria
    defaults: { _controller: ActivoBundle:categoria:index }

categoria_new:
    path:     /categoria/new
    defaults: { _controller: ActivoBundle:categoria:new }

categoria_edit:
    path:     /categoria/edit
    defaults: { _controller: ActivoBundle:categoria:edit }

categoria_show:
    path:     /categoria/show
    defaults: { _controller: ActivoBundle:categoria:show }

categoria_index:
    path:     /categoria/index
    defaults: { _controller: ActivoBundle:categoria:index }



