ActivoBundle\Entity\activo:
    type: entity
    table: null
    repositoryClass: ActivoBundle\Repository\activoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        codigo:
            type: string
            length: '50'
        nombre:
            type: string
            length: '50'
        descripcion:
            type: string
            length: '50'
        unidadResponsable:
            type: string
            length: '50'
            column: unidad_responsable
        personaResponsable:
            type: string
            length: '50'
            column: persona_responsable
        ubicacion:
            type: string
            length: '50'
        cantidad:
            type: integer
    lifecycleCallbacks: {  }
