<?php

namespace ActivoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * activoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class activoRepository extends EntityRepository
{
}
