categoria_index:
    path:     /
    defaults: { _controller: "ActivoBundle:categoria:index" }
    methods:  GET

categoria_show:
    path:     /{id}/show
    defaults: { _controller: "ActivoBundle:categoria:show" }
    methods:  GET

categoria_new:
    path:     /new
    defaults: { _controller: "ActivoBundle:categoria:new" }
    methods:  [GET, POST]

categoria_edit:
    path:     /{id}/edit
    defaults: { _controller: "ActivoBundle:categoria:edit" }
    methods:  [GET, POST]

categoria_delete:
    path:     /{id}/delete
    defaults: { _controller: "ActivoBundle:categoria:delete" }
    methods:  DELETE
